# Generated by Django 3.0.6 on 2020-05-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200508_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Importance'),
        ),
    ]
